// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockInvestment.Infrastructure.Data;

#nullable disable

namespace StockInvestment.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260119165932_AddNotificationChannelConfig")]
    partial class AddNotificationChannelConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockInvestment.Domain.Entities.AIInsight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Confidence")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DismissedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DismissedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reasoning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("StopLoss")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TargetPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TickerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DismissedAt")
                        .HasFilter("[DismissedAt] IS NULL");

                    b.HasIndex("DismissedByUserId");

                    b.HasIndex("GeneratedAt");

                    b.HasIndex("TickerId");

                    b.HasIndex("Type");

                    b.HasIndex("TickerId", "Type", "GeneratedAt");

                    b.ToTable("AIInsights", (string)null);
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.AIModelConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Settings")
                        .HasColumnType("text");

                    b.Property<int>("UpdateFrequencyMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AIModelConfigs", (string)null);
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.AIModelPerformance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Accuracy")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageResponseTimeMs")
                        .HasColumnType("double precision");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer");

                    b.Property<string>("FeatureType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ModelConfigId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AIModelPerformances", (string)null);
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Threshold")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("TickerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Timeframe")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TickerId");

                    b.HasIndex("UserId");

                    b.ToTable("Alerts", (string)null);
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.AnalyticsEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityType")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<string>("Method")
                        .HasColumnType("text");

                    b.Property<long?>("ResponseTimeMs")
                        .HasColumnType("bigint");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AnalyticsEvents");
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.ChartSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChartType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Drawings")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Indicators")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeRange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Symbol")
                        .IsUnique();

                    b.ToTable("ChartSettings", (string)null);
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.CorporateEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalData")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StockTickerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventDate");

                    b.HasIndex("StockTickerId");

                    b.HasIndex("StockTickerId", "EventDate");

                    b.ToTable("CorporateEvents", (string)null);

                    b.HasDiscriminator<int>("EventType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.DataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .HasColumnType("text");

                    b.Property<string>("Config")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChecked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataSources", (string)null);
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("EmailVerificationTokens", (string)null);
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.FinancialReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Quarter")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TickerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TickerId");

                    b.ToTable("FinancialReports", (string)null);
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.Layout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsShared")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShareCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Layouts", (string)null);
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.News", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImpactAssessment")
                        .HasColumnType("text");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Sentiment")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<Guid?>("TickerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TickerId");

                    b.ToTable("News", (string)null);
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.NotificationChannelConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EnabledSlack")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnabledTelegram")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("SlackWebhookUrl")
                        .HasColumnType("text");

                    b.Property<string>("TelegramChatId")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("NotificationChannelConfigs", (string)null);
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.NotificationTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("NotificationTemplates", (string)null);
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AvgPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GainLoss")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GainLossPercentage")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Shares")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Symbol");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Symbol");

                    b.ToTable("Portfolios", (string)null);
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.PushNotificationConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppId")
                        .HasColumnType("text");

                    b.Property<string>("Config")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ServerKey")
                        .HasColumnType("text");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PushNotificationConfigs", (string)null);
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.StockTicker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Change")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ChangePercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("Exchange")
                        .HasColumnType("integer");

                    b.Property<string>("Industry")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PreviousClose")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Value")
                        .HasColumnType("numeric");

                    b.Property<long?>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("StockTickers", (string)null);
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.TechnicalIndicator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IndicatorType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TickerId")
                        .HasColumnType("uuid");

                    b.Property<string>("TrendAssessment")
                        .HasColumnType("text");

                    b.Property<decimal?>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("TickerId");

                    b.ToTable("TechnicalIndicators", (string)null);
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.UserPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreferenceKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferenceValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PreferenceKey")
                        .IsUnique();

                    b.ToTable("UserPreferences", (string)null);
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.Watchlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Watchlists", (string)null);
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Workspaces", (string)null);
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.WorkspaceLayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AddedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LayoutId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LayoutId");

                    b.HasIndex("WorkspaceId", "LayoutId")
                        .IsUnique();

                    b.ToTable("WorkspaceLayouts", (string)null);
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.WorkspaceMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkspaceId", "UserId")
                        .IsUnique();

                    b.ToTable("WorkspaceMembers", (string)null);
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.WorkspaceMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("WorkspaceMessages", (string)null);
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.WorkspaceWatchlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AddedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WatchlistId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WatchlistId");

                    b.HasIndex("WorkspaceId", "WatchlistId")
                        .IsUnique();

                    b.ToTable("WorkspaceWatchlists", (string)null);
                });

            modelBuilder.Entity("StockTickerWatchlist", b =>
                {
                    b.Property<Guid>("TickersId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WatchlistsId")
                        .HasColumnType("uuid");

                    b.HasKey("TickersId", "WatchlistsId");

                    b.HasIndex("WatchlistsId");

                    b.ToTable("WatchlistTickers", (string)null);
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.AGMEvent", b =>
                {
                    b.HasBaseType("StockInvestment.Domain.Entities.CorporateEvent");

                    b.Property<string>("Agenda")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("MeetingTime")
                        .HasColumnType("interval");

                    b.Property<DateTime?>("RecordDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.DividendEvent", b =>
                {
                    b.HasBaseType("StockInvestment.Domain.Entities.CorporateEvent");

                    b.Property<decimal?>("CashDividend")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DividendPerShare")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("ExDividendDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RecordDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("StockDividendRatio")
                        .HasColumnType("numeric");

                    b.ToTable("CorporateEvents", t =>
                        {
                            t.Property("RecordDate")
                                .HasColumnName("DividendEvent_RecordDate");
                        });

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.EarningsEvent", b =>
                {
                    b.HasBaseType("StockInvestment.Domain.Entities.CorporateEvent");

                    b.Property<decimal?>("EPS")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NetProfit")
                        .HasColumnType("numeric");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Revenue")
                        .HasColumnType("numeric");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.ToTable("CorporateEvents", t =>
                        {
                            t.Property("Year")
                                .HasColumnName("EarningsEvent_Year");
                        });

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.RightsIssueEvent", b =>
                {
                    b.HasBaseType("StockInvestment.Domain.Entities.CorporateEvent");

                    b.Property<decimal>("IssuePrice")
                        .HasColumnType("numeric");

                    b.Property<long>("NumberOfShares")
                        .HasColumnType("bigint");

                    b.Property<string>("Purpose")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RecordDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RightsRatio")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubscriptionEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SubscriptionStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.ToTable("CorporateEvents", t =>
                        {
                            t.Property("RecordDate")
                                .HasColumnName("RightsIssueEvent_RecordDate");
                        });

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.StockSplitEvent", b =>
                {
                    b.HasBaseType("StockInvestment.Domain.Entities.CorporateEvent");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsReverseSplit")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RecordDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SplitRatio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("CorporateEvents", t =>
                        {
                            t.Property("RecordDate")
                                .HasColumnName("StockSplitEvent_RecordDate");
                        });

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.AIInsight", b =>
                {
                    b.HasOne("StockInvestment.Domain.Entities.User", "DismissedByUser")
                        .WithMany("DismissedAIInsights")
                        .HasForeignKey("DismissedByUserId");

                    b.HasOne("StockInvestment.Domain.Entities.StockTicker", "Ticker")
                        .WithMany("AIInsights")
                        .HasForeignKey("TickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DismissedByUser");

                    b.Navigation("Ticker");
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.Alert", b =>
                {
                    b.HasOne("StockInvestment.Domain.Entities.StockTicker", "Ticker")
                        .WithMany("Alerts")
                        .HasForeignKey("TickerId");

                    b.HasOne("StockInvestment.Domain.Entities.User", "User")
                        .WithMany("Alerts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticker");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.ChartSettings", b =>
                {
                    b.HasOne("StockInvestment.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.CorporateEvent", b =>
                {
                    b.HasOne("StockInvestment.Domain.Entities.StockTicker", "StockTicker")
                        .WithMany("CorporateEvents")
                        .HasForeignKey("StockTickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockTicker");
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.HasOne("StockInvestment.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.FinancialReport", b =>
                {
                    b.HasOne("StockInvestment.Domain.Entities.StockTicker", "Ticker")
                        .WithMany("FinancialReports")
                        .HasForeignKey("TickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticker");
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.Layout", b =>
                {
                    b.HasOne("StockInvestment.Domain.Entities.User", "User")
                        .WithMany("Layouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockInvestment.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId");

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.News", b =>
                {
                    b.HasOne("StockInvestment.Domain.Entities.StockTicker", "Ticker")
                        .WithMany("News")
                        .HasForeignKey("TickerId");

                    b.Navigation("Ticker");
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.NotificationChannelConfig", b =>
                {
                    b.HasOne("StockInvestment.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.Portfolio", b =>
                {
                    b.HasOne("StockInvestment.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.TechnicalIndicator", b =>
                {
                    b.HasOne("StockInvestment.Domain.Entities.StockTicker", "Ticker")
                        .WithMany("TechnicalIndicators")
                        .HasForeignKey("TickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticker");
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.UserPreference", b =>
                {
                    b.HasOne("StockInvestment.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.Watchlist", b =>
                {
                    b.HasOne("StockInvestment.Domain.Entities.User", "User")
                        .WithMany("Watchlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.Workspace", b =>
                {
                    b.HasOne("StockInvestment.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.WorkspaceLayout", b =>
                {
                    b.HasOne("StockInvestment.Domain.Entities.Layout", "Layout")
                        .WithMany()
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockInvestment.Domain.Entities.Workspace", "Workspace")
                        .WithMany("Layouts")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Layout");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.WorkspaceMember", b =>
                {
                    b.HasOne("StockInvestment.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockInvestment.Domain.Entities.Workspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.WorkspaceMessage", b =>
                {
                    b.HasOne("StockInvestment.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockInvestment.Domain.Entities.Workspace", "Workspace")
                        .WithMany("Messages")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.WorkspaceWatchlist", b =>
                {
                    b.HasOne("StockInvestment.Domain.Entities.Watchlist", "Watchlist")
                        .WithMany()
                        .HasForeignKey("WatchlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockInvestment.Domain.Entities.Workspace", "Workspace")
                        .WithMany("Watchlists")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Watchlist");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("StockTickerWatchlist", b =>
                {
                    b.HasOne("StockInvestment.Domain.Entities.StockTicker", null)
                        .WithMany()
                        .HasForeignKey("TickersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockInvestment.Domain.Entities.Watchlist", null)
                        .WithMany()
                        .HasForeignKey("WatchlistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.StockTicker", b =>
                {
                    b.Navigation("AIInsights");

                    b.Navigation("Alerts");

                    b.Navigation("CorporateEvents");

                    b.Navigation("FinancialReports");

                    b.Navigation("News");

                    b.Navigation("TechnicalIndicators");
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.User", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("DismissedAIInsights");

                    b.Navigation("Layouts");

                    b.Navigation("Watchlists");
                });

            modelBuilder.Entity("StockInvestment.Domain.Entities.Workspace", b =>
                {
                    b.Navigation("Layouts");

                    b.Navigation("Members");

                    b.Navigation("Messages");

                    b.Navigation("Watchlists");
                });
#pragma warning restore 612, 618
        }
    }
}
